targets:
  $default:
    builders:
      freezed:
        options:
          union_key: runtimeType
          union_value_case: none
          buildTo: source
          build_extensions:
            {
              "^{{path}}/{{file}}.dart": "{{path}}/generated/{{file}}.freezed.dart",
            }
      source_gen:combining_builder:
        options:
          build_extensions:
            { "^{{path}}/{{file}}.dart": "{{path}}/generated/{{file}}.g.dart" }
