// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWpGjgEqsRS2hfVlV_H6wbuUQKKKzGxXM',
    appId: '1:1070844573766:android:aaa2509cca56a61da2b247',
    messagingSenderId: '1070844573766',
    projectId: 'discordreplicate',
    databaseURL: 'https://discordreplicate-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'discordreplicate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAameCdZv5GyLApaKhZ24QHu6NdI-4Esec',
    appId: '1:1070844573766:ios:65d9eed875d81032a2b247',
    messagingSenderId: '1070844573766',
    projectId: 'discordreplicate',
    databaseURL: 'https://discordreplicate-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'discordreplicate.appspot.com',
    iosClientId: '1070844573766-hauv9k4s5rk5t7jcblkt3i1r8bfgkshe.apps.googleusercontent.com',
    iosBundleId: 'com.example.discordUiPractice',
  );
}
